# Generated by Django 5.2 on 2025-04-24 16:23

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='FirmwareVersion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('version', models.CharField(max_length=50)),
                ('file_path', models.CharField(max_length=255)),
                ('hash', models.CharField(max_length=64)),
                ('signature', models.TextField(blank=True, null=True)),
                ('is_signed', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Vehicle',
            fields=[
                ('vin', models.CharField(max_length=17, primary_key=True, serialize=False)),
                ('owner_email', models.EmailField(max_length=254)),
                ('phone', models.CharField(blank=True, max_length=15, null=True)),
                ('owner_role', models.CharField(default='PRIMARY', max_length=20)),
                ('dealer_code', models.CharField(default='eDelivery', max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='SecurityLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('event_type', models.CharField(choices=[('AUTH', 'Authentication'), ('API', 'API Access'), ('OTA', 'Firmware Update'), ('CAN', 'CAN Bus Activity'), ('ATTACK', 'Attack Attempt')], max_length=10)),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True)),
                ('description', models.TextField()),
                ('success', models.BooleanField(default=True)),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('vehicle', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='api.vehicle')),
            ],
        ),
    ]
